apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "datanika.fullname" . }}-dbt-projects
  labels:
    {{- include "datanika.labels" . | nindent 4 }}
    app.kubernetes.io/component: dbt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.app.dbtProjectsSize }}
