{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "datanika.fullname" . }}-postgres
  labels:
    {{- include "datanika.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgres
      port: {{ .Values.postgres.port | default 5432 }}
      targetPort: postgres
  selector:
    {{- include "datanika.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
