"""add catalog_entries table

Revision ID: d5d30abce35c
Revises: a1b2c3d4e5f6
Create Date: 2026-02-17 14:32:56.570448
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5d30abce35c"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "catalog_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "entry_type",
            sa.Enum(
                "SOURCE_TABLE", "DBT_MODEL", name="catalogentrytype", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column(
            "origin_type",
            sa.Enum("PIPELINE", "TRANSFORMATION", name="nodetype", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("origin_id", sa.BigInteger(), nullable=False),
        sa.Column("table_name", sa.String(length=255), nullable=False),
        sa.Column("schema_name", sa.String(length=255), nullable=False),
        sa.Column("dataset_name", sa.String(length=255), nullable=False),
        sa.Column("connection_id", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("columns", sa.JSON(), nullable=True),
        sa.Column("dbt_config", sa.JSON(), nullable=True),
        sa.Column("org_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_catalog_entries_org_id"), "catalog_entries", ["org_id"], unique=False)
    op.alter_column(
        "pipelines",
        "dlt_config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "transformations",
        "tests_config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "transformations",
        "tests_config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "pipelines",
        "dlt_config",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.drop_index(op.f("ix_catalog_entries_org_id"), table_name="catalog_entries")
    op.drop_table("catalog_entries")
    # ### end Alembic commands ###
