"""PII separation, release N (expand): the three *_pii sidecars + email_change_requests.

``docs/specs/SPEC_PII_SEPARATION.md`` §4 release **N**, tracked as core#655.

Every operation here is on the expand/contract policy's "safe now" list, and the one that
looks like an exception is not: **the new UNIQUE on ``user_pii.email``** is safe despite
the general rule, because the table is created empty in this same migration and backfilled
from a column that already carries a UNIQUE — there is no value that can violate it.

⚠️ **Dropping the NOT NULLs is what makes N+1 possible at all.** It is a widening, not a
tightening: the previously deployed code keeps writing a value and never notices the
constraint is gone. Leave them on and N+1's code cannot stop writing the legacy columns —
an INSERT that omits ``users.email`` fails immediately. It is *also* what makes
``erase_user`` step 1a possible in N (§0.2): during the dual-write window an erasure has
to NULL the legacy copies as well as delete the PII row, or every erasure until N+2
deletes the copy and leaves the original — while criterion 8, ``get_user_by_email``, login
and every UI surface all still read as erased.

Table manifest for this release (§7 criterion 1e), which the core#809 hazard makes worth
writing down: this migration may CREATE ``user_pii``, ``invitation_pii``,
``notification_channel_pii``, ``email_change_requests``; may ALTER ``users`` and
``invitations``; and may DROP **nothing**. ``audit_log_pii`` must not appear (§2a/D11 —
it would protect a column empty in every production row).

⚠️ Criterion 1e's discriminating rule reads *"``op.drop_table(`` must appear ZERO times in
every migration of this chain"*. Taken literally that forbids an expand release from
being revertible — this one creates four tables, and a ``create_table`` with no matching
``drop_table`` in ``downgrade()`` is a broken downgrade that ``test_roundtrip.py`` fails.
The rule's *purpose* is the core#809 hazard, which is a spurious autogenerated drop of a
**live** table in the **upgrade** path, and that is where ``test_expand_contract_policy.py``
already draws the line: *"downgrade() is ignored — it is destructive by definition and
never runs in the t1 window."* So: **zero ``op.drop_table`` in ``upgrade()``**, here and in
N+2, where the contract release drops columns. Raised on the issue.

expand-contract: EXPAND phase. Nothing is removed or tightened in ``upgrade()``. The NOT
    NULL drops are widenings the previously deployed code cannot notice; the legacy
    columns are dropped in N+2, two releases after the code that stops writing them.

Revision ID: e7f2a9c4b1d8
Revises: d4e9f1a6b3c7
Create Date: 2026-09-02
"""

import sqlalchemy as sa
from alembic import op

revision: str = "e7f2a9c4b1d8"
down_revision: str | None = "d4e9f1a6b3c7"
branch_labels: str | None = None
depends_on: str | None = None

# Rollback stashes, mirroring `a7b8c9d0e1f2`'s `_ROLLBACK_STASH`. They exist only between
# a `downgrade()` and the next `upgrade()`; no released version of the application reads
# them, and the re-upgrade consumes and drops them.
#
# Why they are needed at all, which is worth stating because it is the one genuinely
# irreversible thing in this release. Most of what the sidecars hold is dual-written, so a
# re-upgrade's backfill reconstructs `email`, `full_name` and `oauth_provider_id` from the
# legacy columns exactly. Two things have **no legacy source**: `user_pii.pending_email`
# and the whole of `email_change_requests` — both belong to D8, which is new in this
# release. Without a stash, `downgrade -1` → `upgrade head` silently loses every in-flight
# email change, and `test_data_preservation_roundtrip.py` is the only thing that would
# ever say so. Criterion 0e item 2 asks for exactly this choice to be made deliberately:
# re-derive where you can, and declare `one_way` only where you cannot. Here we can.
_PENDING_EMAIL_STASH = "pii_pending_email_rollback_stash"
_EMAIL_CHANGE_STASH = "email_change_requests_rollback_stash"


def upgrade() -> None:
    op.create_table(
        "user_pii",
        sa.Column("user_id", sa.BigInteger(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=False),
        sa.Column("oauth_provider_id", sa.String(255), nullable=True),
        sa.Column("pending_email", sa.String(320), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
        # Declared inline rather than via `op.create_unique_constraint`, which
        # `test_expand_contract_policy.py` flags as destructive — correctly in general,
        # since old code may still be writing duplicates. It cannot here: the table is
        # created empty in this statement.
        sa.UniqueConstraint("email", name="uq_user_pii_email"),
    )

    op.create_table(
        "invitation_pii",
        sa.Column(
            "invitation_id", sa.BigInteger(), sa.ForeignKey("invitations.id"), nullable=False
        ),
        sa.Column("email", sa.String(320), nullable=False),
        sa.PrimaryKeyConstraint("invitation_id"),
    )

    op.create_table(
        "notification_channel_pii",
        sa.Column(
            "channel_id",
            sa.BigInteger(),
            sa.ForeignKey("notification_channels.id"),
            nullable=False,
        ),
        sa.Column("recipient", sa.String(320), nullable=False),
        sa.PrimaryKeyConstraint("channel_id"),
    )

    op.create_table(
        "email_change_requests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("token_hash", sa.String(64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_email_change_requests_token_hash",
        "email_change_requests",
        ["token_hash"],
        unique=True,
    )

    # D3: the invitation token stops being a plaintext JWT at rest. Added nullable and
    # backfilled below; the legacy `token` column keeps being written through N, because
    # the previously deployed code looks invitations up by equality on it, and is dropped
    # in N+2.
    op.add_column("invitations", sa.Column("token_hash", sa.String(64), nullable=True))
    op.create_index("ix_invitations_token_hash", "invitations", ["token_hash"], unique=True)

    # ── backfills ──────────────────────────────────────────────────────────────
    #
    # ⚠️ These move real rows. `users.email` is populated in 5 of 5 production rows, so
    # this is NOT the audit-payload backfill that §2c deleted — do not conflate them.
    # Criterion 2 is the count check; `test_data_preservation_roundtrip.py` is the value
    # check. Both, not either.
    op.execute(
        """
        INSERT INTO user_pii (user_id, email, full_name, oauth_provider_id)
        SELECT id, email, full_name, oauth_provider_id
        FROM users
        WHERE email IS NOT NULL AND full_name IS NOT NULL
        ON CONFLICT (user_id) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO invitation_pii (invitation_id, email)
        SELECT id, email FROM invitations WHERE email IS NOT NULL
        ON CONFLICT (invitation_id) DO NOTHING
        """
    )
    # EMAIL channels deliver to config->>'email'; Telegram to config->>'chat_id'
    # (`notification_state.py:85-87`, `notification_service.py:143/174`). The Slack
    # webhook URL and the Telegram bot token stay in `config` — they are secrets, an org
    # property rather than personal data, and folding them in here would imply that
    # erasure must decrypt secrets, which §2's scope table forbids.
    op.execute(
        """
        INSERT INTO notification_channel_pii (channel_id, recipient)
        SELECT id, COALESCE(config->>'email', config->>'chat_id')
        FROM notification_channels
        WHERE COALESCE(config->>'email', config->>'chat_id') IS NOT NULL
        ON CONFLICT (channel_id) DO NOTHING
        """
    )
    # `sha256()` is built into Postgres 11+, so this needs no extension. It must agree
    # byte-for-byte with `hashlib.sha256(raw.encode("utf-8")).hexdigest()`, which is what
    # `convert_to(token, 'UTF8')` pins — a bare `token::bytea` would depend on the server
    # encoding instead.
    op.execute(
        """
        UPDATE invitations
        SET token_hash = encode(sha256(convert_to(token, 'UTF8')), 'hex')
        WHERE token IS NOT NULL AND token_hash IS NULL
        """
    )

    # ── put back whatever a previous downgrade() set aside ─────────────────────
    #
    # Absent on a first install, which is the normal case, hence IF EXISTS.
    op.execute(
        f"""
        DO $$
        BEGIN
            IF to_regclass('{_PENDING_EMAIL_STASH}') IS NOT NULL THEN
                UPDATE user_pii p
                SET pending_email = s.pending_email
                FROM {_PENDING_EMAIL_STASH} s
                WHERE s.user_id = p.user_id;
                DROP TABLE {_PENDING_EMAIL_STASH};
            END IF;
            IF to_regclass('{_EMAIL_CHANGE_STASH}') IS NOT NULL THEN
                INSERT INTO email_change_requests
                SELECT * FROM {_EMAIL_CHANGE_STASH};
                -- The ids are restored verbatim, so the identity sequence has to be
                -- moved past them or the next insert collides on the primary key.
                PERFORM setval(
                    pg_get_serial_sequence('email_change_requests', 'id'),
                    GREATEST(COALESCE((SELECT max(id) FROM email_change_requests), 0), 1)
                );
                DROP TABLE {_EMAIL_CHANGE_STASH};
            END IF;
        END $$;
        """
    )

    # ── the widenings that make N+1 and erasure step 1a possible ───────────────
    op.alter_column("users", "email", existing_type=sa.String(320), nullable=True)
    op.alter_column("users", "full_name", existing_type=sa.String(255), nullable=True)
    op.alter_column("invitations", "email", existing_type=sa.String(320), nullable=True)
    op.alter_column("invitations", "token", existing_type=sa.String(500), nullable=True)

    op.get_bind().commit()


def downgrade() -> None:
    # Set aside the two things that have no legacy source, before the tables holding them
    # are dropped. See the module-level note on the stashes.
    op.execute(
        f"CREATE TABLE {_PENDING_EMAIL_STASH} AS "
        "SELECT user_id, pending_email FROM user_pii WHERE pending_email IS NOT NULL"
    )
    op.execute(f"CREATE TABLE {_EMAIL_CHANGE_STASH} AS SELECT * FROM email_change_requests")

    # Re-derive the legacy columns from the sidecars before restoring NOT NULL. Without
    # this a rollback fails on any row created after the expand by code that had already
    # stopped writing them — and it fails at the constraint, naming a column rather than
    # the reason.
    op.execute(
        """
        UPDATE users u
        SET email = COALESCE(u.email, p.email),
            full_name = COALESCE(u.full_name, p.full_name),
            oauth_provider_id = COALESCE(u.oauth_provider_id, p.oauth_provider_id)
        FROM user_pii p
        WHERE p.user_id = u.id
        """
    )
    op.execute(
        """
        UPDATE invitations i
        SET email = COALESCE(i.email, p.email)
        FROM invitation_pii p
        WHERE p.invitation_id = i.id
        """
    )

    op.alter_column("invitations", "token", existing_type=sa.String(500), nullable=False)
    op.alter_column("invitations", "email", existing_type=sa.String(320), nullable=False)
    op.alter_column("users", "full_name", existing_type=sa.String(255), nullable=False)
    op.alter_column("users", "email", existing_type=sa.String(320), nullable=False)

    op.drop_index("ix_invitations_token_hash", table_name="invitations")
    op.drop_column("invitations", "token_hash")

    op.drop_index("ix_email_change_requests_token_hash", table_name="email_change_requests")
    op.drop_table("email_change_requests")
    op.drop_table("notification_channel_pii")
    op.drop_table("invitation_pii")
    op.drop_table("user_pii")

    op.get_bind().commit()
