"""The image probe's own logic, tested (core#602).

`scripts/probe_built_image.py` needs Docker and a built image, so it runs in its
own **informational** CI job. These tests cover its pure functions only — no
Docker, milliseconds — so the parsing and comparison the probe's verdict rests on
are themselves gated by the normal `test` job.

That split matters. The probe is the thing asserting on the artifact nothing
asserted on; if its comparator silently returned "no drift" for everything, the
job would go green and we would be exactly where core#602 started. Every case
below is written in both directions: the comparator must find real drift **and**
must not invent it.
"""

from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

_MODULE_PATH = Path(__file__).resolve().parents[2] / "scripts" / "probe_built_image.py"


def _load():
    spec = importlib.util.spec_from_file_location("probe_built_image", _MODULE_PATH)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


probe = _load()


def test_the_probe_script_exists_where_ci_expects_it():
    """The CI job invokes this path by string; a rename would 404 silently."""
    assert _MODULE_PATH.is_file(), f"{_MODULE_PATH} is missing"


class TestNormalize:
    def test_pep503_equivalence(self):
        assert probe.normalize("Foo_Bar") == probe.normalize("foo-bar")
        assert probe.normalize("zope.interface") == "zope-interface"
        assert probe.normalize("  Requests ") == "requests"

    def test_distinct_names_stay_distinct(self):
        assert probe.normalize("mcp") != probe.normalize("mcpx")


class TestParsePins:
    def test_reads_uv_export_output(self):
        text = """\
# This file was autogenerated by uv
--index-url https://pypi.org/simple
anyio==4.4.0
httpx==0.27.2 ; python_full_version >= '3.8'
pydantic==2.9.2
"""
        pins = probe.parse_pins(text)
        assert pins == {"anyio": "4.4.0", "httpx": "0.27.2", "pydantic": "2.9.2"}

    def test_ignores_flags_comments_and_blanks(self):
        assert probe.parse_pins("\n# c\n--hash=sha256:abc\n\n-e .\n") == {}

    def test_normalizes_names_on_the_way_in(self):
        assert probe.parse_pins("Zope.Interface==6.0\n") == {"zope-interface": "6.0"}

    def test_an_unreadable_line_is_skipped_not_fatal(self):
        """A parser that dies on an unfamiliar flag becomes a permanently red
        job, and a permanently red job gets deleted."""
        pins = probe.parse_pins("--some-future-flag\nanyio==4.4.0\n???\n")
        assert pins == {"anyio": "4.4.0"}


class TestPinDrift:
    def test_finds_the_core_602_shape(self):
        """The unlocked graft install moved a package the lock had pinned."""
        drift = probe.pin_drift({"mcp": "1.9.4"}, {"mcp": "2.0.1"})
        assert drift == [("mcp", "1.9.4", "2.0.1")]

    def test_finds_collateral_movement_not_just_mcp(self):
        """The reason this is not `assert mcp < 2`.

        `datanika-mcp` declares an unbounded `httpx>=0.27` too, and that resolve
        reaches anyio / pydantic / starlette / uvicorn. A version assert on one
        package would call this image clean.
        """
        locked = {"mcp": "1.9.4", "httpx": "0.27.2", "anyio": "4.4.0"}
        installed = {"mcp": "1.9.4", "httpx": "0.28.1", "anyio": "4.6.0"}
        assert probe.pin_drift(locked, installed) == [
            ("anyio", "4.4.0", "4.6.0"),
            ("httpx", "0.27.2", "0.28.1"),
        ]

    def test_a_matching_version_is_not_drift(self):
        assert probe.pin_drift({"anyio": "4.4.0"}, {"anyio": "4.4.0"}) == []

    def test_a_locked_package_absent_from_the_image_is_not_drift(self):
        """The image installs `--no-dev`; dev-only deps are legitimately gone.

        Reporting those would bury the real finding under dozens of lines, and a
        noisy probe gets ignored long before it gets fixed.
        """
        assert probe.pin_drift({"pytest": "8.0.0", "anyio": "4.4.0"}, {"anyio": "4.4.0"}) == []

    def test_an_installed_package_the_lock_omits_is_not_drift(self):
        """`datanika-cloud` and `datanika-mcp` install from source, not the lock."""
        installed = {"anyio": "4.4.0", "datanika-mcp": "0.2.0"}
        assert probe.pin_drift({"anyio": "4.4.0"}, installed) == []

    def test_empty_inputs_do_not_crash(self):
        assert probe.pin_drift({}, {}) == []
        assert probe.pin_drift({}, {"anyio": "4.4.0"}) == []

    def test_drift_is_reported_in_a_stable_order(self):
        """An unstable order makes two runs' logs diff against each other."""
        locked = {"zzz": "1", "aaa": "1", "mmm": "1"}
        installed = {"zzz": "2", "aaa": "2", "mmm": "2"}
        assert [d[0] for d in probe.pin_drift(locked, installed)] == ["aaa", "mmm", "zzz"]


class TestTheDriftCheckCannotPassVacuously:
    """A drift check over an empty intersection is a green that proves nothing.

    That is the defect this whole probe exists to close, and it would be
    embarrassing to reproduce it one layer up: if the pin export silently
    produced nothing, `pin_drift` returns `[]` and check C prints "no drift".
    """

    def test_zero_locked_pins_is_a_collapse(self):
        assert probe.comparison_collapsed({}, {"anyio": "4.4.0"})

    def test_zero_installed_packages_is_a_collapse(self):
        assert probe.comparison_collapsed({"anyio": "4.4.0"}, {})

    def test_a_tiny_overlap_is_a_collapse(self):
        """Both sides populated but barely intersecting — an export/platform mismatch."""
        locked = {f"pkg{i}": "1.0" for i in range(80)}
        installed = {"pkg1": "1.0", "unrelated": "2.0"}
        assert probe.comparison_collapsed(locked, installed)

    def test_a_real_overlap_is_not_a_collapse(self):
        shared = {f"pkg{i}": "1.0" for i in range(60)}
        assert probe.comparison_collapsed(shared, dict(shared)) is None

    def test_the_floor_is_where_it_says_it_is(self):
        at_floor = {f"pkg{i}": "1.0" for i in range(probe._MIN_COMPARED)}
        assert probe.comparison_collapsed(at_floor, dict(at_floor)) is None
        below = {f"pkg{i}": "1.0" for i in range(probe._MIN_COMPARED - 1)}
        assert probe.comparison_collapsed(below, dict(below))

    def test_the_reason_is_returned_not_just_a_bool(self):
        """The log has to say which way it collapsed, or triage starts blind."""
        assert "zero pins" in probe.comparison_collapsed({}, {"a": "1"})
        assert "zero installed" in probe.comparison_collapsed({"a": "1"}, {})


class TestLastLine:
    def test_ignores_output_emitted_before_our_print(self):
        assert probe.last_line('DeprecationWarning: ...\n{"a": "1"}\n') == '{"a": "1"}'

    def test_handles_trailing_blank_lines(self):
        assert probe.last_line("ok\n\n\n") == "ok"

    def test_empty_output_is_empty_not_an_exception(self):
        assert probe.last_line("") == ""
        assert probe.last_line("\n \n") == ""


class TestTheProbeInterrogatesTheVenvAsBuilt:
    def test_it_does_not_reach_for_bare_uv_run(self):
        """⚠️ `uv run python` re-syncs from the lock.

        That would *repair* the drift inside the container before measuring it,
        and report a clean image that is not clean — a green that would look
        identical had the thing failed. The fallback must carry `--no-sync`.
        """
        source = _MODULE_PATH.read_text(encoding="utf-8")
        import re

        for match in re.finditer(r'"uv",\s*"run",\s*("(?:[^"]*)")', source):
            assert match.group(1) == '"--no-sync"', (
                "a `uv run` invocation in the probe does not pass --no-sync "
                "immediately after `run`, so it can re-sync the venv it is "
                "supposed to be measuring"
            )

    def test_it_prefers_the_venv_interpreter_directly(self):
        source = _MODULE_PATH.read_text(encoding="utf-8")
        assert "/app/.venv/bin/python" in source

    def test_it_imports_the_submodules_not_just_the_package(self):
        """The observed failure was raised from inside `datanika_mcp.server`.

        `import datanika_mcp` alone can succeed while the mount still fails, so
        the probe must walk the same chain `datanika/datanika.py` does.
        """
        snippet = probe._MCP_IMPORT_SNIPPET
        for submodule in ("datanika_mcp.client", "datanika_mcp.server", "datanika_mcp.session"):
            assert submodule in snippet, f"{submodule} missing from the import probe"

    def test_the_container_runs_without_network(self):
        """Nothing here should be able to reach the internet and self-heal."""
        source = _MODULE_PATH.read_text(encoding="utf-8")
        assert '"--network", "none"' in source


class TestTheProbeIsNotJustAVersionAssert:
    def test_it_does_not_gate_on_an_mcp_version_number(self):
        """core#602's filed mechanism was wrong and a version assert inherits it.

        `mcp < 2` would not catch a rename within the 1.x line, and says nothing
        about anyio / httpx / pydantic / starlette / uvicorn, which the same
        unlocked resolve can move. If someone later "simplifies" this probe into
        a version comparison, this test is what argues back.
        """
        source = _MODULE_PATH.read_text(encoding="utf-8")
        assert "failures.append" in source
        # The version is printed as context, never compared.
        assert "__version__" in source
        assert "< 2" not in source.split('"""', 2)[-1], (
            "the probe appears to gate on an mcp version number instead of the import"
        )


@pytest.mark.parametrize(
    "locked,installed,expected",
    [
        ({"a": "1"}, {"a": "1"}, 0),
        ({"a": "1"}, {"a": "2"}, 1),
        ({"a": "1", "b": "2"}, {"a": "9", "b": "9"}, 2),
    ],
)
def test_drift_count_is_what_the_verdict_rests_on(locked, installed, expected):
    assert len(probe.pin_drift(locked, installed)) == expected
